### ISSUE TITLE
Make project-less ServerRuntime possible

### ISSUE THREAD

**Issue by andrus** [nhl/bootique-cayenne#12]
Sometimes we want an empty Cayenne stack... Nothing wrong with that, the app should not fail. Currently it does:

```
Caused by: org.apache.cayenne.configuration.server.DataDomainLoadException: [v.4.0.M3 Feb 08 2016 16:38:05] Configuration resource "cayenne-project.xml" is not found.
	at org.apache.cayenne.configuration.server.DataDomainProvider.descriptorFromConfigs(DataDomainProvider.java:198)
	at org.apache.cayenne.configuration.server.DataDomainProvider.createAndInitDataDomain(DataDomainProvider.java:110)
```

Perhaps on bq-cayenne side we set the default dynamically. If "cayenne-project.xml" is present on classpath, we use that. If not, we revert to project-less stack (with a note in the logs).

**Comment by andrus** [comment]
## UPGRADE NOTES

This is a breaking change. ```CayenneModule.builder``` is removed, as it no longer serves any useful purpose (its "noConfig" method is the same as the absence of cayenne-project.xml on classpath), but it made impossible clean implementation of this feature.
